#!/usr/bin/env bash
THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
if [[ ! -d polaris-build/scripts ]];
then
    git submodule update --init --remote polaris-build
fi
polaris-build/scripts/package_operations.sh ${THIS_DIR} "$@"
