"""add_col_changelog_to_work_items

Revision ID: 3b9eec79e130
Revises: c995ddf29ad6
Create Date: 2023-11-16 15:13:23.976398

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3b9eec79e130'
down_revision = 'c995ddf29ad6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_items', sa.Column('changelog', postgresql.JSONB(astext_type=sa.Text()), nullable=True), schema='work_tracking')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_items', 'changelog', schema='work_tracking')
    # ### end Alembic commands ###
