"""add_sprints_column_to_work_items

Revision ID: 45713333a0fe
Revises: dc7185193c09
Create Date: 2023-08-09 01:33:52.968131

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '45713333a0fe'
down_revision = 'dc7185193c09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_items', sa.Column('sprints', postgresql.ARRAY(sa.String()), server_default='{}', nullable=True), schema='work_tracking')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_items', 'sprints', schema='work_tracking')
    # ### end Alembic commands ###
