"""Updates to support commit mapping scope

Revision ID: a9326c356c7f
Revises: e1545ffcfeb9
Create Date: 2018-12-05 16:20:33.445428

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a9326c356c7f'
down_revision = 'e1545ffcfeb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_items_sources', sa.Column('commit_mapping_scope', sa.String(), server_default='organization', nullable=False), schema='work_tracking')
    op.add_column('work_items_sources', sa.Column('commit_mapping_scope_key', postgresql.UUID(as_uuid=True), nullable=False), schema='work_tracking')
    op.drop_column('work_items_sources', 'repository_key', schema='work_tracking')
    op.drop_column('work_items_sources', 'project_key', schema='work_tracking')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_items_sources', sa.Column('project_key', postgresql.UUID(), autoincrement=False, nullable=True), schema='work_tracking')
    op.add_column('work_items_sources', sa.Column('repository_key', postgresql.UUID(), autoincrement=False, nullable=True), schema='work_tracking')
    op.drop_column('work_items_sources', 'commit_mapping_scope_key', schema='work_tracking')
    op.drop_column('work_items_sources', 'commit_mapping_scope', schema='work_tracking')
    # ### end Alembic commands ###
