""" added organization_key column to cached_commits

Revision ID: b6c8ff8e412a
Revises: ab068ed4540f
Create Date: 2018-11-29 15:17:08.723465

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b6c8ff8e412a'
down_revision = 'ab068ed4540f'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column('cached_commits', sa.Column('organization_key', postgresql.UUID(as_uuid=True), nullable=False), schema='work_tracking')
    op.drop_constraint('cached_commits_repository_name_commit_key_key', 'cached_commits', schema='work_tracking', type_='unique')
    op.create_unique_constraint('cached_commits_repository_name_commit_key_organization_key_key', 'cached_commits', ['organization_key', 'repository_name', 'commit_key'], schema='work_tracking')



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cached_commits_repository_name_commit_key_organization_key_key', 'cached_commits', schema='work_tracking', type_='unique')
    op.create_unique_constraint('cached_commits_repository_name_commit_key_key', 'cached_commits', ['repository_name', 'commit_key'], schema='work_tracking')
    op.drop_column('cached_commits', 'organization_key', schema='work_tracking')

