"""Added last_synced column to WorkItemSource

Revision ID: d37d16c40f5d
Revises: 43480869648d
Create Date: 2019-01-31 14:29:52.483203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd37d16c40f5d'
down_revision = '43480869648d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_items_sources', sa.Column('last_synced', sa.DateTime(), nullable=True), schema='work_tracking')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_items_sources', 'last_synced', schema='work_tracking')
    # ### end Alembic commands ###
