"""Add last_sync column to work_items

Revision ID: e1545ffcfeb9
Revises: b6c8ff8e412a
Create Date: 2018-12-05 15:26:08.931642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1545ffcfeb9'
down_revision = 'b6c8ff8e412a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_items', sa.Column('last_sync', sa.DateTime(), nullable=True), schema='work_tracking')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_items', 'last_sync', schema='work_tracking')
    # ### end Alembic commands ###
