"""drop table WorkItemsCommits

Revision ID: ef7cfbdea63e
Revises: fa688ae1aae9
Create Date: 2018-11-28 19:22:40.554738

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ef7cfbdea63e'
down_revision = 'fa688ae1aae9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_items_commits', schema='work_tracking')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_items_commits',
    sa.Column('work_items_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('commit_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('repository_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('commit_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('commit_branch', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('commit_message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['work_items_id'], ['work_tracking.work_items.id'], name='work_items_commits_work_items_id_fkey'),
    sa.PrimaryKeyConstraint('work_items_id', 'commit_key', name='work_items_commits_pkey'),
    schema='work_tracking'
    )
    # ### end Alembic commands ###
