"""added WorkItemsCommit to model

Revision ID: fa688ae1aae9
Revises: db00b206309e
Create Date: 2018-11-26 23:56:04.484139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa688ae1aae9'
down_revision = 'db00b206309e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_items_commits',
    sa.Column('work_items_id', sa.BigInteger(), nullable=False),
    sa.Column('commit_key', sa.String(), nullable=False),
    sa.Column('repository_name', sa.String(), nullable=False),
    sa.Column('commit_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('commit_branch', sa.String(), nullable=True),
    sa.Column('commit_message', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['work_items_id'], ['work_tracking.work_items.id'], ),
    sa.PrimaryKeyConstraint('work_items_id', 'commit_key'),
    schema='work_tracking'
    )
    op.create_index(op.f('ix_work_tracking_work_items_commits_work_items_id'), 'work_items_commits', ['work_items_id'], unique=False, schema='work_tracking')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_tracking_work_items_commits_work_items_id'), table_name='work_items_commits', schema='work_tracking')
    op.drop_table('work_items_commits', schema='work_tracking')
    # ### end Alembic commands ###
